# Generated by Django 4.1.2 on 2024-11-10 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage",
                        to="base.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
